### ISSUE TITLE
data-rel="dialog" seems to be broken in 1.2.0

### ISSUE THREAD

**Issue by h0ru5** [opitzconsulting/jquery-mobile-angular-adapter#100]
Hi,

great library!
But i was puzzeled quite some time until i realized taht due to the hash-magic, the dioalg seems to be broken.

see this fiddle:
http://jsfiddle.net/Y6pkm/7/

it should work like this:
http://jquerymobile.com/test/docs/pages/dialog/index.html

best regards,
Johannes

**Comment by tbosch** [comment]
Hi,
this is a known issue and cannot be fixed easily: Please use a `data-role="dialog"` on the dialog div, instead of `data-role="page"` (background: currently, a page can only be either a dialog or a page, but not both, as in plain jquery mobile). Here is your fiddle with the mentioned changes:

http://jsfiddle.net/Y6pkm/9/

Tobias

**Comment by h0ru5** [comment]
Wow, that was quick!

Thanks, using the suggested workaround i got it running. 

On Chrome, I get some exceptions in the console, but seems to be no problem.

Error: An attempt was made to break through the security policy of the user agent.
    at Browser.self.url (file:///.../js/angular.js:3051:30)

Johannes

**Comment by tbosch** [comment]
Hi,
try again serving your site with a web server. There should be no more problems then...

Tobias

**Comment by h0ru5** [comment]
Hi,

yes, I did figure out i'ts related to ajax and file:// policies, so server-served sites should be ok.

However, my target is a pseudo-native app using PhoneGap, so I am limited there. If this should really cause problems at some point  (seems not so uptil now), I can serve some mark-up from the server as well.

But its really a great lib you provide, thank you!

Johannes
