### ISSUE TITLE
Problem with jquery rating plugin.

### ISSUE THREAD

**Issue by jaumeavila** [opitzconsulting/jquery-mobile-angular-adapter#101]
When using the jquery rating plugin (http://www.fyneworks.com/jquery/star-rating/) inside an ng-repeat there are some issues.

If ng-repeat is not used, it is displayed correctly.
Here there is an example without the ng-repeat:
http://jsfiddle.net/SmkUr/2/

And here there is the same example but using ng-repeat.
http://jsfiddle.net/RPwKD/1/

As you can see, the stars should be displayed in different li items but they don't.

Jaume

**Comment by tbosch** [comment]
Hi,
the rating plugin is not part of jquery mobile, so the adapter does not spport it, sorry :-(
Basically, you have to create your own angular directive. There are a lot of tutorials out there how this can be accomplished in general.
Closing this, as not related to jquery mobile.

Tobias
