### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by marcorinck** [opitzconsulting/jquery-mobile-angular-adapter#108]
Hi, 

we are currently developing an application in our company with this adapter and legal department asks what license is used to distribute the adapter. 

I couldn't find a license file in code ... so what should I tell them?  :-)

Thanks

**Comment by tbosch** [comment]
Hi,
it's MIT license, as angular, jquery and jquery mobile.
The non minified version contains a comment in the header referencing the license.
But you are right: I should note this in the Readme.md!

Tobias

Am 14.01.2013 um 13:20 schrieb "romulus23" <notifications@github.com<mailto:notifications@github.com>>:

Hi,

we are currently developing an application in our company with this adapter and legal department asks what license is used to distribute the adapter.

I couldn't find a license file in code ... so what should I tell them? :-)

Thanks

**Comment by marcorinck** [comment]
Thank you!

Maybe put a LICENSE file in project root, as that seems to be common sense in many node.js packages.

**Comment by tbosch** [comment]
Just added a LICENSE file.
