### ISSUE TITLE
Support for JQM 1.3

### ISSUE THREAD

**Issue by avandijk** [opitzconsulting/jquery-mobile-angular-adapter#115]
Hi,

Is the angular adapter compatible with the new version of JQM 1.3 which is now in beta officially?

thx
Arjan

**Comment by tbosch** [comment]
Hi,
sorry, not yet. Didn't have time. However, if you could try, collect bugs and report them, this would help a lot for the next version!

Tobias

**Comment by mlegenhausen** [comment]
+1
I will collect bugs ;)
We would need this support in around one month.

**Comment by avandijk** [comment]
Ok I'll collect bugs also as I am about to implement angular adapter for the first time in my apps

**Comment by tbosch** [comment]
@mlegenhausen: Should be doable to support jqm 1.3 around mid of March or so...

**Comment by cranst0n** [comment]
+1

**Comment by westlane** [comment]
+1

**Comment by mlegenhausen** [comment]
As generell information, we are currently porting our app to jqm 1.3 and have no bugs at all with the jqm-angular-adapter. We are currently using a single file with all pages inside, but there are other issues when loading them dynamically. The only problems we had were with the integration of the new widgets like the panels, which we solved by building our own directives.

**Comment by jperl** [comment]
:+1:

**Comment by jonathancochran** [comment]
Thanks for all you work on this adapter, tigbro! I'm curious if you're optimistic about a mid march release still? I built a frontend ui around 1.3 but ran into various issues with the new widgets and wasn't able to figure out how to upgrade the adapter to support the new widgets.

**Comment by tbosch** [comment]
Still possible!

Am 26.02.2013 um 21:44 schrieb "couchinteractive" <notifications@github.com<mailto:notifications@github.com>>:

Thanks for all you work on this adapter, tigbro! I'm curious if you're optimistic about a mid march release still? I built a frontend ui around 1.3 but ran into various issues with the new widgets and wasn't able to figure out how to upgrade the adapter to support the new widgets.

**Comment by tbosch** [comment]
Hi, 
introduced a new provider `jqmNgWidgetProvider`, with which all widget adapters are written. By this, it should be fairly simple to move on to jqm 1.3. See https://github.com/tigbro/jquery-mobile-angular-adapter/#integrating-custom-jquery-mobile-plugins-with-angular

Tobias

**Comment by ds82** [comment]
There is a problem with the listview as well. It's not rendered by jqm at all:

http://jsfiddle.net/ds82/ZHKBA/100/

If you change jqm from 1.3 to 1.2 in this example it works fine.

**Comment by tbosch** [comment]
Hi ds82,
your listview example is now working again!

Tobias

**Comment by tbosch** [comment]
Closing this, preparing for release 1.3.0 of the adapter.
