### ISSUE TITLE
Max call stack size exceeded when loading external html page using jQuery Mobile 1.3.0b1

### ISSUE THREAD

**Issue by btesser** [opitzconsulting/jquery-mobile-angular-adapter#117]
I believe the issue is happening somewhere within the connecToDocument loop.  The external page XHR finishes but nothing renders and the page dies.
HTML link which initiates issue: <a href="/reports.html" >Reports</a>

XHR finished loading: "http://localhost:1337/reports.html". jquery-1.9.0.min.js:3
Uncaught RangeError: Maximum call stack size exceeded
st.extend.camelCase
i
st.extend.data
$.widget.bridge.$.fn.(anonymous function)
st.extend.each
st.fn.st.each
$.widget.bridge.$.fn.(anonymous function)
$.mobile.registerJqmNgWidget.jqmWidgets.(anonymous function)
ng.directive.restrict
execWithFlag
preventJqmWidgetCreation
ng.directive.restrict
execWithFlag
markJqmWidgetCreation
(anonymous function)
connectToDocument
ng.directive.restrict
ng.config.directiveTemplateUrls
$.mobile.registerJqmNgWidget.jqmWidgets.(anonymous function)
(anonymous function)
connectToDocument
ng.directive.restrict
ng.config.directiveTemplateUrls
$.mobile.registerJqmNgWidget.jqmWidgets.(anonymous function)
(anonymous function)
connectToDocument
![Screen Shot 2013-01-23 at 4 50 07 PM](https://f.cloud.github.com/assets/830336/91615/ed2193d6-65a6-11e2-9372-bf654a4926fa.png)

**Comment by tbosch** [comment]
Hi,
right now, the adapter does not support jquery mobile 1.3 beta yet. But thanks for providing this error. 
It would be great if you could report other problems with jquery mobile 1.3b when you find them.

Tobias

**Comment by ds82** [comment]
Any known workarounds for this, yet?

I have the same issue and created a plunk to reproduce it:
http://plnkr.co/edit/3BFrDybrguIgmsgLEDwt?p=preview

**Comment by btesser** [comment]
I scrapped the idea of using it.  Ended up just using angular and Twitter
bootstrap for css

**Comment by tbosch** [comment]
Hi,
next thing I am working on the adapter is jqm 1.3 support. Should be ready in about 2 weeks or so.
Until now, I refactored the routing and added the new `ngmWidgetProvider` service, by which it gets easy to include custom jQuery Mobile plugins into the adapter.

Tobias

**Comment by tbosch** [comment]
Hi,
with the latest commit I updated to jqm 1.3. Your plunk is now working: http://plnkr.co/edit/3BFrDybrguIgmsgLEDwt?p=preview

Could you double check?
Thanks,
Tobias

**Comment by tbosch** [comment]
Closing this, preparing for release 1.3.0 of the adapter.
