### ISSUE TITLE
Popups on dialog closing the dialog

### ISSUE THREAD

**Issue by davidd4** [opitzconsulting/jquery-mobile-angular-adapter#118]
When a popup on a dialog closes (e.g. an item is selected from a selectmenu), the dialog is closed.
This behavior is caused by 

```
function instrumentPopupCloseToNavigateBackWhenDialogUrlIsSet() {
```

**Comment by tbosch** [comment]
Hi,
yes, your are right. This works when using plain jquery mobile...

Tobias

**Comment by tbosch** [comment]
Please have a look at here when using dialogs in dialogs or poups in dialogs and the back button: https://github.com/tigbro/jquery-mobile-angular-adapter#widget-dialog

**Comment by tbosch** [comment]
Here is a jsfiddle with a working version, using 1.2.1-SNAPSHOT.
http://jsfiddle.net/ZHKBA/96/

**Comment by davidd4** [comment]
nice
thx
