### ISSUE TITLE
nested lists

### ISSUE THREAD

**Issue by alexiusp** [opitzconsulting/jquery-mobile-angular-adapter#123]
It seems that nested lists (in jQueryMobile) dont work with angular and this adapter.
JQM creates links for nested lists wich looks like #/html/somepage.html&ui-page=14-0.
And when I try to click this link it redirects me on /html/somepage.html page where I was before click (parameters lost). Is it a problem with Angular routing engine? How it can be solved?

**Comment by tbosch** [comment]
Hi,
in jqm 1.3 nested lists are deprecated, and support will be dropped in jqm 1.4 (see here: http://jquerymobile.com/blog/2013/02/20/jquery-mobile-1-3-0-released/). The suggestion is to implement nested listviews just an own page.

I am leaving this open to remove all old support for nested listviews from the adapter.

Thanks,
Tobias

**Comment by tbosch** [comment]
Removed support for nested list views by the last commit, which updated to jqm 1.3. 
Closing this.
