### ISSUE TITLE
pristine state not respected for form input range

### ISSUE THREAD

**Issue by rodcloutier** [opitzconsulting/jquery-mobile-angular-adapter#126]
Upon creation, input of type range are not set to pristine like other input types when min is specified.

See fiddle http://jsfiddle.net/rodcloutier/PT8YL/1/

**Comment by tbosch** [comment]
Yes, 
that's a bug. 
Thanks for reporting!

Tobias

**Comment by tbosch** [comment]
Hi,
by the way, slider now uses numbers in the scope (just like `<input type="number">`), and no more strings. 

Thanks for reporting!
Tobias
