### ISSUE TITLE
data-role="none" not respected within a directive

### ISSUE THREAD

**Issue by kellyje** [opitzconsulting/jquery-mobile-angular-adapter#136]
data-role="none" doesn't seem to be respected inside of a directive, but works as intended outside. I've tried setting data-enhance and the default jqm init values as well, but nothing seems to work.

jsFiddle: http://jsfiddle.net/aBPM6/2/

I couldn't get it working outside of the directive in the jsfiddle, but it seems to work outside with the application I'm working on.  I'm also relatively new to both angular/jquery mobile, so let me know if I'm just not setting something correctly.

Thanks

**Comment by tbosch** [comment]
Hi,
thanks for reporting. Yes, I could verify this as a bug.

Tobias

**Comment by tbosch** [comment]
Thanks for reporting.
Here is an updated jsfiddle (using jqm1.3 by the way, as the adapter has been upgraded in the mean time...): http://jsfiddle.net/tigbro/aBPM6/3/

Tobias
