### ISSUE TITLE
Form inputs are not rendered properly with jqm 1.3

### ISSUE THREAD

**Issue by rodcloutier** [opitzconsulting/jquery-mobile-angular-adapter#139]
Hi,

I know jqm 1.3 is a work in progress but the current version breaks the form inputs rendering.

See fiddle http://jsfiddle.net/ZHKBA/114/

**Comment by tbosch** [comment]
Hi,
your fiddle contained the wrong css version: 1.3.0 instead of 1.2.0:
http://jsfiddle.net/ZHKBA/115/

I will update the issue template for the adapter...

Thanks,
Tobias

**Comment by rodcloutier** [comment]
Good. I should have thought about that!
