### ISSUE TITLE
table widget: add refresh support

### ISSUE THREAD

**Issue by tbosch** [opitzconsulting/jquery-mobile-angular-adapter#142]
Jqm 1.3 introduced the `table` widget. However, it does not yet have a `refresh` method, see here: https://github.com/jquery/jquery-mobile/issues/5570. Waiting for jqm 1.3.1 to implement this...

**Comment by jperl** [comment]
:+1: (added a comment to watch this)

**Comment by tbosch** [comment]
Just updated to jqm 1.3.1 and the jqm table widget seems to refresh properly now. @jperl Could you also do some tests?

Thanks,
Tobias

**Comment by jperl** [comment]
@tigbro Sure!

**Comment by tbosch** [comment]
As far as I see this is working now, I also added tests for this.
Closing...
