### ISSUE TITLE
JQM widget only being rendered the first time in a directive test

### ISSUE THREAD

**Issue by jperl** [opitzconsulting/jquery-mobile-angular-adapter#146]
I am attempting to do directive testing in the style of the [ng-directive-testing](https://github.com/vojtajina/ng-directive-testing/blob/master/test/tabsSpec.js) project.

[Here](https://github.com/jperl/angular-jquery-mobile/blob/master/test/unit/todoSpec.js) is my spec.

The first and second test are identical, but they output different html.

The [first test](https://github.com/jperl/angular-jquery-mobile/blob/master/test/unit/todoSpec.js#L18) outputs 

`<div class="ui-checkbox"><label for="checked" class="ng-binding ui-checkbox-on ui-btn ui-btn-up-c ui-btn-corner-all ui-fullsize ui-btn-icon-null" data-corners="true" data-shadow="false" data-iconshadow="true" data-wrapperels="span" data-icon="checkbox-on" data-iconpos="null" data-theme="c" data-mini="false"><span class="ui-btn-inner"><span class="ui-btn-text">First</span><span class="ui-icon ui-icon-checkbox-on ui-icon-shadow">&nbsp;</span></span></label><input type="checkbox" ng-model="todo.completed" id="checked" data-ngm-checkboxradio="[]" class="ng-pristine ng-valid"></div>`.

The [second test](https://github.com/jperl/angular-jquery-mobile/blob/master/test/unit/todoSpec.js#L29) outputs

`<input type="checkbox" ng-model="todo.completed" id="checked" class="ng-pristine ng-valid">
    <label for="checked" class="ng-binding">First</label>`

Only in the first test the JQM widgets are applied properly. How can I get the directive to render the same way in both tests?

**Comment by jperl** [comment]
~~Wait on answering this, I might have found what I need in [here](https://github.com/tigbro/jquery-mobile-angular-adapter/tree/master/test/unit/integration).~~

**Comment by jperl** [comment]
I updated the tests to use the unittestTools but I still can't figure it out. Please help :)

**Comment by tbosch** [comment]
Hi,
please try again with the angular-mocks that I am using in the adapter (directory test/lib). I am using an older version there, which works well. 

Tobias

**Comment by jperl** [comment]
THANK YOU!!!!!!!!!!!!!
