### ISSUE TITLE
Trouble using JQM Panels

### ISSUE THREAD

**Issue by mikekay01** [opitzconsulting/jquery-mobile-angular-adapter#152]
Has anyone encountered problems using Jquery Mobile panels with this adapter?  I have been trying to get them to work.  They seem to work in a plan JQM project, but the panel content just displays as a plain div with the adapter.

thanks,

**Comment by tbosch** [comment]
Hi,
could you post a jsfiddle for this? You can use this template: http://jsfiddle.net/tigbro/ZHKBA/

Tobias

**Comment by tbosch** [comment]
Hi,
here is a sample using the above template: http://jsfiddle.net/stqNe/1/
The panel content gets styled correctly, as far as I can tell...

Does this help you?

Tobias

**Comment by mikekay01** [comment]
I basically took your "todo" sample and tried to add a panel to it, but it doesn't work.  I tried using the jsFiddle template you send but couldn't load it into jsFiddle.  

Can you place a panel in your todo example so I can see what I'm doing wrong?

thx,

**Comment by tbosch** [comment]
Hi,
the problem was that the todo example used jquery mobile 1.2, and that does not contain the panel widget.
Just updated the todo example, should work now... http://jsfiddle.net/tigbro/Du2DY/

Tobias

**Comment by mikekay01** [comment]
I just downloaded the todo example and it seems to be the same.  Are you sure it was changed?

I downloaded from your gitHub page.

thx,

mike…

**Comment by mikekay01** [comment]
I will work from the jsFiddle, no need to change the toDo if you don't want.  thx...

**Comment by tbosch** [comment]
Well,
there are two of them: 
1. The js fiddle here: http://jsfiddle.net/tigbro/Du2DY/, which I updated to the current lib
2. The todo-mobile GitHub-Repo here: https://github.com/tigbro/todo-mobile, which is still old.

Tobias

**Comment by tbosch** [comment]
Closing this...
