### ISSUE TITLE
[Popups] losing transition and position

### ISSUE THREAD

**Issue by hsdk123** [opitzconsulting/jquery-mobile-angular-adapter#170]
I'm noticing that the popups I've made through jQuery undergo the following changes when I add the adapter:
1. Default position changes from [right next to the button pressed that triggers the popup] to [screen centre].
2. I lose the transitions I've set on the popup (ex. data-transition="pop")

Here's a jsFiddle to illustrate:

http://jsfiddle.net/ZHKBA/133/

It would be nice if we could 1. keep the default position instead of moving popups to the centre of the screen, 2. get back transitions for more responsive UI.

Links:
http://jquerymobile.com/demos/1.2.0-alpha.1/docs/pages/popup/
QuoteFromJqueryDoc: "By default, popups open centered vertically and horizontally over the thing you clicked (the origin) which is good for popups used as tooltips or menus"

**Comment by tbosch** [comment]
Hi,
thanks for submitting this! This really is a bug. Will care for it soon.

Tobias

**Comment by hsdk123** [comment]
Thanks for the fast reply, it's great to know that this is in active development!

**Comment by hsdk123** [comment]
Is there perhaps a quick workaround to this? I'm currently trying to persuade some co-workers to switch over to Angular and use the adapter here for jqm and this is currently the only issue preventing me.

**Comment by tbosch** [comment]
Hi,
this should be very easy to correct. However, I have been busy these days... Will look at it next week...

Tobias

**Comment by hsdk123** [comment]
Thanks for the reply, hope things calm down for you over the next week.

**Comment by tbosch** [comment]
Hi,
your jsfiddle is now working as expected...

Tobias

**Comment by hsdk123** [comment]
Thanks for the fix, my team and I have now completely moved over to using Angular and the adapter!

**Comment by tbosch** [comment]
Your welcome!

Am 27.04.2013 um 02:44 schrieb "daegon123" <notifications@github.com<mailto:notifications@github.com>>:

Thanks for the fix, my team and I have now completely moved over to using Angular and the adapter!
