### ISSUE TITLE
resolve not working in routeProvider

### ISSUE THREAD

**Issue by asgeo1** [opitzconsulting/jquery-mobile-angular-adapter#172]
I'm trying to inject some data into my controller via the 'resolve' feature of the angularjs router.  It's not working, I suspect because the jquery-mobile-angular-adapter does not support this?

I created a plunk here:

http://plnkr.co/edit/mMHH7J6AWMx0Q6VxLIzw

Have I done something wrong, or is this just not supported in the jqm-ng-adapter ?

**Comment by tbosch** [comment]
Hi,
with the jqm adapter, you can't inject properties form `resolve` into the constructor function of the controller, as pages and their controllers may be cached. Please use the `onActivate` feature instead.
Have a look here: http://plnkr.co/edit/1LB01Rlz551uNHVKjgMb

There are more details in the Readme.md: https://github.com/tigbro/jquery-mobile-angular-adapter#navigation-and-routes

Does this solve your problem?
Tobias

**Comment by tbosch** [comment]
Hope this helped. Closing this.
