### ISSUE TITLE
Models destroyed on slider (range), possibly other widgets...

### ISSUE THREAD

**Issue by jonathancochran** [opitzconsulting/jquery-mobile-angular-adapter#175]
When the jqm widgets are rendered to the view, the associated model seems to be destroyed. If you remove the two  inputs in my plunker example, the model works as intended. 

Give it a sec to load (it downloads the standalone adapter):
http://plnkr.co/edit/3o3EZVLIkys47scGGFtZ?p=preview

**Comment by tbosch** [comment]
Yes, I can verify this. The slider should take the value 15 as it's initial value...

**Comment by tbosch** [comment]
Thanks for submitting!
