### ISSUE TITLE
Explanation with routeProvider

### ISSUE THREAD

**Issue by polizinha** [opitzconsulting/jquery-mobile-angular-adapter#176]
Hello... I'm trying to use ur adapter but I'm having troubles :S
I can't render new pages using routeProvider.

Here plunker if u can help show me the way.

http://plnkr.co/edit/ptp0BkOljzbfHIgWptMQ

Thanks in advance

**Comment by tbosch** [comment]
Hi,
there was a doublequote missing when you imported jquery mobile:
instead of 

```
<script type="text/javascript" src=http://code.jquery.com/mobile/1.3.1/jquery.mobile-1.3.1.min.js"></script>
```

Use 

```
<script type="text/javascript" src="http://code.jquery.com/mobile/1.3.1/jquery.mobile-1.3.1.min.js"></script>
```

See here: http://plnkr.co/edit/NHYEhIJlKVfdhDM7AM1B?p=preview

Closing this...

Tobias

**Comment by polizinha** [comment]
sorry for my mistake. But fixing it load page, but don't load new one when click.

http://plnkr.co/edit/DNGiT83csWMmfYnHXOop

**Comment by popcorn245** [comment]
Your links cannot contain # tags. Change the tgt on each of your $scope.options as just list instead of #/list. Either link your pages with the router as you have done or use jquery mobile built in way, as so, #link and add a page with a corresponding id.

**Comment by alejandrocao** [comment]
Hi, 

Could you explain the solution to the issue? I'm having the same problem to move from one page to another using the routeProvider (I need to send a parameter for the second page). 
Could you correct the Plunker or create a new one?

Thanks in advance,
Alejandro

**Comment by ocdemo** [comment]
Hi,
here is an updated plnkr.co. Chrome changed it's security policy recently, so you need to use https://rawgithub ... links if you want to include sources directly from Github.

Here is a working version: http://plnkr.co/edit/tPxW3jqYmL0FhBcQooCQ?p=preview

Tobias
