### ISSUE TITLE
Incorrect buttons behaviour in a fieldset controlgroup

### ISSUE THREAD

**Issue by rodcloutier** [opitzconsulting/jquery-mobile-angular-adapter#177]
Selecting the last buttons does not always update the model or trigger the radio group behaviour (same behaviour with 3 items), unless the model is being used in the page. ie: using a `<pre ng-show="0">{{$scope.my_value}}</pre>` will restore the right behaviour.

Fiddle to show the issue. http://jsfiddle.net/rodcloutier/ZHKBA/137/

Contrast with straight Angular JS

http://jsfiddle.net/rodcloutier/sLYvx/

If you add another fieldset, the behaviour is now even stranger since clicking in a fieldset will sometimes result in a change in another field set.

Uncomment the Boolean fieldset in previous fiddle or see http://jsfiddle.net/rodcloutier/ZHKBA/136/

**Comment by tbosch** [comment]
Hi,
thanks for reporting! Realized that `scope.$evalAsync` might be evaluated not until the next `scope.$digest`, which is too late. The adapter used it to minimize the calls to the `refresh` functions of the jqm widgets. I created a new extension `scope.$postDigestOne` to call functions after digesting.

Your fiddle works now as expected.

Tobias
