### ISSUE TITLE
Refresh on custom route.

### ISSUE THREAD

**Issue by rohankadam284** [opitzconsulting/jquery-mobile-angular-adapter#178]
Hello. Nice work with the adapter.
I am facing the following issue.
I have declared a custom route as follows
var abc = angular.module("abc", ["ngResource"]).
    config(function($routeProvider) {
        $routeProvider.when('/details/:id', {
    templateUrl:'test.html',
    jqmOptions: { transition: 'pop' }
});
it works fine from within the index.html when I provide the route details/123. But when I put something like /details/123 in the browser it won't work. As a result refresh for that route  won't work.

Kindly please let me know if I am doing something wrong. Thank You

**Comment by popcorn245** [comment]
There is nothing wrong with your code or the undesired function of the refresh. The author is working on a fix for true hash-bangs (/#!/), but nothing as of yet. As I have done, I would recommend just pushing forward and hope for a bugfix to alleviate the issue. I have tried myself to fix it, but apparently I am not as verbose in javascript as the author.

**Comment by tbosch** [comment]
Hi,
The adapter enabled `$locationProvider.html5Mode(true)` by default, as this is also the default behavior of jquery mobile. However, unless you have server support for this, you can't enter that routing url directly into the browser location. Have a look at the angular docs for `$locationProvider.html5Mode`: http://docs.angularjs.org/guide/dev_guide.services.$location

If you want hash bang urls, you can turn html5Mode off using `$locationProvider.html5Mode(false)`.
Hope this helps and sorry for the late answer,
Tobias

**Comment by tbosch** [comment]
Closing this...
