### ISSUE TITLE
$http not working when controller called via onActivate

### ISSUE THREAD

**Issue by SethArchambault** [opitzconsulting/jquery-mobile-angular-adapter#182]
When I had the ng-controller definited onActivate and not on the page, trying to use $http.get did not work.  Once I added it to the page and removed it from onActivate, it worked again.  What's up with that?

**Comment by tbosch** [comment]
Hi,
sorry, I don't get your problem... Could you crate a jsfiddle for this? The readme.md contains a template...

Thanks,
Tobias

**Comment by tbosch** [comment]
Closing this. Please reopen if you still have problems...
