### ISSUE TITLE
Showing multiple active pages 

### ISSUE THREAD

**Issue by sandkumar** [opitzconsulting/jquery-mobile-angular-adapter#187]
Hi, I am designing an application with navigation menus and content as separate pages. As this is targeted for a tablet device, I would like to display the current navigation page on the left and simultaneously, the content page on the right.

I understand that the adapter maintains only one active page to improve performance (jsfiddle: http://jsfiddle.net/sandkumar/Y7U9D/4/ -- page2 does not react to changes to $scope.text). I have been able to work around this by overriding $scope.$parent.$disconnect in my controller.

Kindly suggest if there is a better solution to achieve the same result. Thanks!

**Comment by tbosch** [comment]
Hi,
yes, this is the only possible workaround yet.
I am curious: How does this work in plain jquery mobile, especially with changing pages?

Tobias

**Comment by tbosch** [comment]
Just as a note: jquery mobile also only has one active page, `$.mobile.activePage`.

**Comment by tbosch** [comment]
Could you show some docs that plain jquery mobile supports this, especially with changing pages?
I don't want to introduce new features in the adapter that are not supported by jquery mobile...

**Comment by sandkumar** [comment]
Hi, Thanks for your quick response! You are perhaps right that jquery-mobile does not support this. I could not find any documentation. 
Attaching a similar jsfiddle without angular:  http://jsfiddle.net/sandkumar/7bVCM/1/

**Comment by tbosch** [comment]
Hi,
I think you'll be fine with the workaround you mentioned. 
However, as jquery mobile does not support this, I will not introduce a new feature in the adapter for this (unless I get a lot of votes :-) ).

Closing this...
