### ISSUE TITLE
JS Fiddle / Plunker example in README not working

### ISSUE THREAD

**Issue by SethArchambault** [opitzconsulting/jquery-mobile-angular-adapter#192]
The Readme says to report an issue with JSFiddle, but the JSFiddle is not working in it's initial state:

http://jsfiddle.net/doercreator/mAxhX/1/

Looking in the console, I found the error:

```
Refused to execute script from 'https://github.com/opitzconsulting/jquery-mobile-angular-adapter/raw/master/compiled/jquery-mobile-angular-adapter-standalone.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled. 
```

I tried replacing this with: 

```
https://raw.github.com/opitzconsulting/jquery-mobile-angular-adapter/master/compiled/jquery-mobile-angular-adapter-standalone.js
```

But that didn't work either - github uses the MIME type 'text/plain'.  

So we need this hosted somewhere before JSFiddle is useable for submitting errors!  

Once this is done, I can see if I can replicate an error I'm having, and submit it if necessary.  Thanks!

UPDATE:
Same problem exists with Plunker

**Comment by tbosch** [comment]
Hi,
what Browser are you using? I just checked with current Firefox (v20) and Chrome (v26) and it's working there, only with a warning. 
This seems the be documented here: https://code.google.com/p/chromium/issues/detail?id=180007

Solution mentioned in the tracker: use this link: 
https://rawgithub.com/opitzconsulting/jquery-mobile-angular-adapter/master/compiled/jquery-mobile-angular-adapter-standalone.js

I will update the fiddle soon.
Thanks!

Tobias

**Comment by SethArchambault** [comment]
Chrome v27  on Mac OS

Cool! that rawgithub link works!

**Comment by SethArchambault** [comment]
I should note that the JSFiddle and Plunker example in ReadMe _work_ (technically) in their current condition, _until_ you add any code that requires angular.. Probably shoulda made that more clear.

**Comment by tbosch** [comment]
Created new jsfiddle and plunk. Closing this...
