### ISSUE TITLE
integration of jquery mobile datebox

### ISSUE THREAD

**Issue by ghost** [opitzconsulting/jquery-mobile-angular-adapter#198]
Hi tigbro, would it be possible for you to help out with this issue? There is one directly related to using jqm-angular-adapter with datebox here.

https://github.com/jtsage/jquery-mobile-datebox/issues/272

It seems there are different people in a close spot of time looking at having a working jqm datepicker together with angularjs. I guess this is would be a really nice feature. Thanks for any comments/ideas/hints!

**Comment by tbosch** [comment]
Hi,
sorry for the late reply. I will look into this soon, promised :-)

Tobias

**Comment by ghost** [comment]
Hi Tobias!

That's great news, thanks a lot. If I could, I would (and in future maybe I will) help. But right now I'm just trying to get into all this stuff about JavaScript, Angular, jQuery mobile and so on.... I guess I missed out the last 10 years of bleeding edge web technologies :-)

Anyway, I'll try to make up to your efforts if and when I can. Thanks again!

Günther

**Comment by tbosch** [comment]
I found the problem and fixed it. 
After the previous commit, the original jsfiddle is now working as expected: http://jsfiddle.net/UsYju/6/
Changes:
- use `rawgithub` hostname to include jqm script so it also runs in Chrome
- change `"useNewstyle":"true"` to `"useNewstyle":true`

Could you double check and the close the issue?
Thanks,
Tobias

**Comment by ghost** [comment]
working nicely, thanks!!
