### ISSUE TITLE
angular generated listview items do not get jquery mobile styles

### ISSUE THREAD

**Issue by leeahoward** [opitzconsulting/jquery-mobile-angular-adapter#20]
Here is an example I threw together using the todo app:
http://jsfiddle.net/AecvK/
You will notice that the first two items in the list are static and are styled correctly.   The rest of the items are generated by angular and do not get the jqmobile styles..

Here is the working example using adapter version 1.0.4:
http://jsfiddle.net/HYhkX/

Glad to see the update to jqm 1.0.1 so quickly.  . 

Thanks!

**Comment by tbosch** [comment]
Hi,
thanks a lot! I did an internal refactoring of the refreshing logic for issue #17.
I created a ui test case for this, so this should never happen again!

Tobias

**Comment by tbosch** [comment]
By the way, instead of using ngm:event="{pagebeforeshow: 'refreshTodos()', swipeleft:'$navigate(\'settings\')'}" in your example, you can now use ngm:pageforeshow="refreshTodos()" and ngm:swipeleft="$navigate('settings')

Tobias

**Comment by leeahoward** [comment]
Works perfectly so far.   Thanks!
