### ISSUE TITLE
jquery2.0.2 incompatible

### ISSUE THREAD

**Issue by regou** [opitzconsulting/jquery-mobile-angular-adapter#203]
I was using jquery 2.0.2,and an error shows in console when initializing a jqm panel:

> Cannot read property 'options' of undefined
> div data-role="panel" data-opened="panelIsOpen" id="mainPanel" data-position="left" data-display="reveal" data-ngm-panel="[]"  angular.min.js:62

panel cannot working properly
then I switch back to jquery 1.10.1 ,all is fine

maybe not a big deal...

**Comment by tbosch** [comment]
Hi,
just checked against plan jquery mobile, and the same errors occurs: http://jsfiddle.net/Qb4Km/

Please have a look at the issue tracker at jquery mobile and maybe create this tracker there.

Tobias

**Comment by regou** [comment]
OK, I resolved this by change "mobilePage" to "mobile-page" in jquery.mobile-1.3.1.min.js
