### ISSUE TITLE
listview not updated every time when adding or removing data in javascript 

### ISSUE THREAD

**Issue by rodriguezc** [opitzconsulting/jquery-mobile-angular-adapter#208]
Thank you Tobias for your work and for this great adapter! 

The list is not updated every time when I push or remove data from the binded array.

See the fiddler:
http://jsfiddle.net/EsQBa/

**Comment by MartineFrancken** [comment]
I tried to see your problem in the fiddle, but it's working correct for me. When I push data it will add it directly to the listview and when I remove data it will get directly removed from the listview.

**Comment by rodriguezc** [comment]
Thanks Martine. It seems that it occurs occurs only when adding null/empty data to the list.

**Comment by tbosch** [comment]
Hi,
the problem was that initially the field `$scope.newFriend` had the value `undefined` and the adapter did not detect a change when this was added to the array. The previous commit fixes that. 
A workaround would have been to set `$scope.newFriend = null` initially.

Tobias
