### ISSUE TITLE
Uncaught TypeError: Cannot call method 'module' of undefined

### ISSUE THREAD

**Issue by mikekay01** [opitzconsulting/jquery-mobile-angular-adapter#215]
I am getting this error in my project.  Can someone please help resolve?  

I have a Plunkr of the project here:

http://plnkr.co/edit/wv6R3WeXpcpAiiLFH5pb

**Comment by mikekay01** [comment]
This is a very basic project with basically nothing in it, but it seems to get this error.  I am using the standalone version of jquery-mobile-angular-adapter vs CDN because it is a requirement for my project.   Can the developer of this adapter please advise why this error is occuring?

Thanks.

**Comment by ocdemo** [comment]
Hi,
you missed to include angular. So just also add it and it should work.
Or you take the standalone version of the adapter that already includes jquery, jquery mobile, angular and the adapter...

Tobias

**Comment by mikekay01** [comment]
Adding the Angular js script link produces this error:

Uncaught Error: Provider jqmNgWidget must define $get factory method. from ng

**Comment by mikekay01** [comment]
I used the standalone version and everything seems ok.  There must be some inconsistency in the versions I was using.  Thanks for the support.
