### ISSUE TITLE
How to process angular directive after page change

### ISSUE THREAD

**Issue by date80** [opitzconsulting/jquery-mobile-angular-adapter#219]
Hi,

I have an issue with processing custom angular directives after page change. The issue is that directives are not processed at all. I'm may be missing something as I'm new to angular and especially to the specifics of your adapter. Is there a way to trigger processing of custom directives after a new page was loaded from a template?

(Sorry for posting a new issue, I wasn't sure how to ask a question on github by any other means.)

**Comment by sagarSahay** [comment]
Is there any error on your page, i.e. in chrome when you do the page change does any error show up in the console??

**Comment by date80** [comment]
In the meanwhile we "solved" the problem: It seems like the order of the JS includes in our index.html caused the problem. We rearranged them according to an example we found on the net - now everything works as expected. Nevertheless - thanks for your reply!
