### ISSUE TITLE
ngm-if attribute does not refresh jQuery Mobile content

### ISSUE THREAD

**Issue by bender-2000** [opitzconsulting/jquery-mobile-angular-adapter#24]
Attribute widget @ngm-if can be used for adding and removing elements from the DOM. An use case has been found in which element just added is not refreshed as jQM elements dynamically added need to, causing not enhanced elements to appear on screen.

The following example shows this effect:

http://jsfiddle.net/LucasG2000/Ev4AN/

This is the structure of the example and how to reproduce it:
- A controller is created (TestController) which has an ItemCollection which will be used for feeding a jQM ListView.
- Another field of this controller is called IDItemEditable. This field will be used as the condition in the ngm-if for putting a row in edit mode when it is clicked.
- Initially IDItemEditable is null, causing that only content for read-only items is added to the DOM. These entries are enhanced by jQM as expected.
- When one row is clicked, condition changes removing read-only items and adding content for editing the row
  - Expected result: New shown content is jQM enhanced.
  - Obtained result: New shown content is not jQM enhanced, rendering as normal HTML.
- When save button is clicked, condition changes again inverting condition
  - Expected result: Rendering of new content enhanced again by jQM.
  - Obtained result: New shown content is not jQM enhanced again.

I suppose that a refresh method is missing somewhere.

Software versions used:
- jQuery Mobile 1.1.0-rc2
- jQuery 1.7.1
- Angular JS 1.0.0-rc4
- jQuery Mobile Angular Adapter 1.0.7-rc1

Best regards.

**Comment by tbosch** [comment]
Hi,
thanks for submitting, this needs to be fixed! 
Did you try try with angular 1.0.0-rc3? I have tested the jQuey Mobile Adapter 1.0.7-rc1 only against 1.0.0-rc3... However, I will update soon!

Tobias

**Comment by bender-2000** [comment]
Hi Tobias,

Thanks for the prompt reply. Yes, this happens with angular 1.0.0-rc3 too.
Looking forward for next update :)

Best regards.

**Comment by tbosch** [comment]
Just to let you know: I am working on a redesign of the adapter to improve the performance. This will also fix this issue, and should be finished in the next two weeks. I'll keep you updated.

Tobias

**Comment by bender-2000** [comment]
Great to know !

**Comment by tbosch** [comment]
Updated the js fiddle with current angular-version, jquery-mobile and current snapshot of jqm ng adapter: http://jsfiddle.net/Ev4AN/1/
