### ISSUE TITLE
Allow $browser and $location usage from within angular

### ISSUE THREAD

**Issue by tbosch** [opitzconsulting/jquery-mobile-angular-adapter#25]

**Comment by jperl** [comment]
I am assuming that breaks angular's default style of navigation?

Also if you have any guidance on how to get started on this, I'd be willing to take a stab at it.

**Comment by tbosch** [comment]
Hi,
actually, jquery mobile has it's own style of navigation. There you can define what kind of transition you want when a new page is displayed, ... Using angular's location service would not allow this, so most people would not use it.

However, it would be great if you want to investigate on this. First point would be to create a test case to reproduce this.
The easiest way would be a jsfiddle. What do you think?

Tobias

**Comment by jperl** [comment]
Sounds good. I'll take a look this weekend.
