### ISSUE TITLE
Model gets changed after focus get removed

### ISSUE THREAD

**Issue by asutoshdash** [opitzconsulting/jquery-mobile-angular-adapter#29]
Hi,

Following is my code snippet:

http://jsfiddle.net/asu_fiddle/pxBPL/1/

However when I execute this, the model (basically uname) gets chaged once I cahnge the focus out of  name field, please let me know what I am missing in the HTML file.

Thanks in advance
Asutosh

**Comment by tbosch** [comment]
Hi,
this seems to work as expected: You put something into the input field, tab out of the field, and the field gets updated.
If you want to update the model immediately when you type, add a ng-model-instant attribute:

```
<input ng-model="uname"  type="text" placeholder="Name" id="name" ng-model-instant>
```

Please note, that this is no more needed in the current angular version (1.0 rc8). However, the standalone build of the adapter uses angular 1.0rc3. You could try to use the the non standalone build of the adapter together with the newest angular lib. However, I did not tests this yet. I will release a new version of the adapter in the next week which will work with the newest angular version.

Tobias

**Comment by asutoshdash** [comment]
Thanks Tobias, eagerly waiting for the next release which will work with newest angular version.
