### ISSUE TITLE
jQuery Mobile markup fails to render in templateUrl file

### ISSUE THREAD

**Issue by gscottolson** [opitzconsulting/jquery-mobile-angular-adapter#30]
I just added 1.0.7-rc2-SNAPSHOT to my project. It resolves a couple issues I was having, but it introduces another issue:

I have a few directives that include template files via the templateUrl property. Any jQuery Mobile markup within these templates (like a &lt;div data-role="navbar" &gt; element with a nested ;&lt;ul&gt;) is not converted into a jQuery Mobile widget. Instead, this content appears as a regular unstyled unordered list.

There is workaround for this issue. If I use the template property for the directives (instead of using templateUrl), the jQuery Mobile markup is correctly converted to the appropriate jQuery Mobile widget (in the above case, the data-role="navbar" element correctly renders as a jQuery Mobile navbar.

This isn't a huge issue, but it means I have to use embedded templates with my directives. Also, the 1.0.7-rc1 version of this adapter worked with the templateUrl property in my directives. This issues seems to be related to the rc2 changes.

**Comment by gscottolson** [comment]
A note about the workaround (using the template property instead of the templateUrl property):

My template declaration in my directive is...

&lt;div data-role="controlgroup" data-type="horizontal"&gt;
  &lt;a ng-repeat="filter in filterSet" data-role="button"&gt;{{filter.label}}&lt;/a&gt;
&lt;/div&gt;

The ng-repeat directive is properly processed, but markup is not converted into a jQuery Mobile horizontal control group. So... the workaround falls apart if my template has ng directives within a jQuery Mobile component.

**Comment by tbosch** [comment]
Hi, 
yes, I changed the integration logic for performance reasons. This is my main goal in rc2.
Actually, I did not use a template in mobile directives yet. Thanks for reporting this!
Could you create a jsfiddle for that? This helps a lot in creating a test case!

Thanks,
Tobias

**Comment by gscottolson** [comment]
jsFiddle: http://jsfiddle.net/gscottolson/XUKUt/
Gist: https://gist.github.com/2731701

Getting this error:
jquery-mobile-angular-adapter-standalone-1.0.7-rc2-SNAPSHOT.js:22185
Template must have exactly one root element.

After some testing, the root cause seems to be that the response is returning empty, thus causing the error in jqm-angular-adapter. My updated jsFiddle shows other aspects of angular (like data binding) working correctly.

**Comment by tbosch** [comment]
Hi, 
good idea with the integration of a gist in jsfiddle!
However, the gist needs to be named "fiddle.response.html". I created a new gist and updated the jsfiddle.

jsFiddle: http://jsfiddle.net/XUKUt/30/
Gist: https://gist.github.com/2762934

Thanks for reporting this!
Tobias

**Comment by gscottolson** [comment]
Integrated this fix today. Works as expected. Thanks!
