### ISSUE TITLE
ng-model not respected inside of directive

### ISSUE THREAD

**Issue by ghost** [opitzconsulting/jquery-mobile-angular-adapter#31]
I'm using a directive with an ng-model on it, but it is not updating the dom or the value when I update it. From below, I can change the ng-model to text or leave it with the huge parent expression, but neither seems to work.

Insight.module.directive('text', [function() {
    return {
        restrict: 'E',
        scope: {
            parameter: 'accessor'
        },
        template: '<input data-mini="true" ng-model="$parent.$parent.control.Value" type=text jqm-widget=textinput />',
        replace: true,
        compile: function () {

```
        return function (scope, element, attrs) {
            var control = scope.parameter();

            if (control.DefaultValues && control.DefaultValues.length) {
                control.Value = control.DefaultValues[0];
                scope.text = control.Value;
            }
        }

    }
}
```

}]);

**Comment by tbosch** [comment]
Hi,
thanks for reporting this. Which version are you using?
Could you create a jsfiddle for this? This helps a lot in reproducing the problem.

Tobias

**Comment by tbosch** [comment]
Sorry, I don't understand the problem you have. Please provide a jsfiddle. 

Tobias

**Comment by ghost** [comment]
You can close this for the moment, I found a work-around that is cleaner, this doesn't appear to be a problem currently for me any more.

**Comment by tbosch** [comment]
Ok.
If you encounter other errors, feel free to open the issue (or another one) again.

Tobias
