### ISSUE TITLE
Incorrectly rendered jQuery Mobile grouped buttons

### ISSUE THREAD

**Issue by gscottolson** [opitzconsulting/jquery-mobile-angular-adapter#32]
Grouped buttons (both horizontal and vertical) are not rendering correctly in 1.0.7 rc2. They are rendering correctly in 1.0.7 rc1.

Adapter 1.0.7 RC1: http://jsfiddle.net/gscottolson/tzVGj/
Adapter 1.0.7 RC2: http://jsfiddle.net/gscottolson/Lf6Lh/

Also... RC1 has no hover/active state, but RC2 does.

**Comment by tbosch** [comment]
Thanks for reporting! I created a unit test for it, so this should no more happen. 
Keep the bug-reports coming!
