### ISSUE TITLE
Incorrectly rendered jQuery Mobile grouped buttons in templateUrl file

### ISSUE THREAD

**Issue by gscottolson** [opitzconsulting/jquery-mobile-angular-adapter#33]
Thanks for all the bug fixes. I really appreciate it!

Unfortunately, the fix for [bug #32](https://github.com/tigbro/jquery-mobile-angular-adapter/issues/32) doesn't solve the case where the controlgroup is dynamically added via a directive with a templateUrl. The following jsFiddle shows this defect:

http://jsfiddle.net/gscottolson/aDBz5/

Not only are the buttons ungrouped, but the data-type="horizontal" attribute is not being applied.

**Comment by tbosch** [comment]
Thanks again!
By the way, the issue only existed when there was a control group in the html, and another control group was loaded using templateUrl.

Tobias

**Comment by gscottolson** [comment]
Actually, this isn't the use case I'm trying to solve. I thought this represented my issue, but even with the fix for #33 I'm still having problems.

I've got a navigation bar (a set of jQuery Mobile tabs) at the top of the page (being loaded as a templateUrl) and a component that includes a horizontal controlgroup (also being loaded as a templateUrl). I'm still having issues with the controlgroup buttons rendering as individual buttons.

I'm going to try to create this specific use case in a jsFiddle and file another bug. I really appreciate all the help.
