### ISSUE TITLE
ng-model of radio button does not check radio

### ISSUE THREAD

**Issue by gscottolson** [opitzconsulting/jquery-mobile-angular-adapter#38]
I'm following angular's recommended pattern of using the value and ng-model attributes for radio buttons. However, the default radio button (based on the value of the property assigned to ng-model) does not get checked. See the jsfiddle...

http://jsfiddle.net/gscottolson/jQjWL/

**Comment by mtomas** [comment]
Use workaround till it gets resolved:
http://jsfiddle.net/qJq4a/1/

I've also encountered strange behaviour when generating radio buttons using ng-repeat - they are not synchronized to underlying ng-model property and they do not get proper jquery mobile css styles applied..this definitely should get resolved.

**Comment by tbosch** [comment]
Hi, this is the same underlying problem as with #41. 
As your jsfiddle works now with the last commit I close this issue.

Thanks for reporting,
Tobias
