### ISSUE TITLE
Inset listview from ng-repeat does not have rounded corners

### ISSUE THREAD

**Issue by gscottolson** [opitzconsulting/jquery-mobile-angular-adapter#39]
When I render an inset listview using the ng-repeat directive, the resulting listview does not have properly rounded corners.

http://jsfiddle.net/gscottolson/Lfg5u/

Note: in the jsFiddle... if you remove a tag (by clicking) the listview is re-rendered with properly rounded corners.

**Comment by tbosch** [comment]
Yes, you are right, this does not work as expected.

**Comment by tbosch** [comment]
With the last commit works.
