### ISSUE TITLE
Checkbox view does not change with model

### ISSUE THREAD

**Issue by ajoslin** [opitzconsulting/jquery-mobile-angular-adapter#41]
When I set the model for a checkbox to true, the checkbox does not get checked on the view.

Here is what a stripped down example of what I am trying to do: http://jsfiddle.net/andytjoslin/qz7bQ/1/

Where in the jqm-adapter code is the checkbox directive?  I'd take a look at it, but I can't find it.

**Comment by ajoslin** [comment]
Any ideas?

**Comment by tbosch** [comment]
Hi, 
mmh, not so easy: If you use ng-checked it seems to work, with a plain ng-model it does  not. 
I'll look into this.

The widgets are in the file src/main/webapp/integration/jqmAngularWidgets.js However, this only contains the behavior. The directives themselves are generic and in the file src/main/webapp/integration/compileIntegration.js

Tobias

**Comment by tbosch** [comment]
Here is an updated jsfiddle that is using 1.0.7-rc3-SNAPSHOT:
http://jsfiddle.net/qz7bQ/2/
