### ISSUE TITLE
HTML elements outside of the jQuery mobile page break radio button rendering

### ISSUE THREAD

**Issue by jupiterplanet** [opitzconsulting/jquery-mobile-angular-adapter#45]
I have inserted two pairs of divs. One pair before the page and another pair after the page. Both divs cause the rendering to break. The first pair of divs causes the rendering of the button's disabled state to break and the second div causes the rendering of the radio buttons to break.

I use divs this way e. g. for application wide overlays.

See the jsFiddle at http://jsfiddle.net/jupiter/kk7K9/2/.

Change jquery-mobile-angular-adapter-1.0.7-rc2.js to jquery-mobile-angular-adapter-1.0.7-rc1.js to see it work with rc1 or comment or delete the two divs to see it work in rc2. 

I have used jquery mobile 1.1.0 and AngularJS 1.0.0rc9.

**Comment by tbosch** [comment]
Updated fiddle with current versions: http://jsfiddle.net/kk7K9/4/
angular 1.0.1, jqm adapter 1.0.7-rc3-snapshot, jqm 1.1.0

**Comment by tbosch** [comment]
Hi, 
wow, strange behavior! Thanks for reporting.
However, with the current version everything works fine (see the updated jsfiddle).

Tobias
