### ISSUE TITLE
Update to angular-0.10

### ISSUE THREAD

**Issue by tbosch** [opitzconsulting/jquery-mobile-angular-adapter#5]

**Comment by respectTheCode** [comment]
Any progress on this?

**Comment by tbosch** [comment]
Hello Kevin,
I am waiting for the angular team to include the rework of the compiler, and to stabilize the api. Probably, this will not be the case until angular 1.0.
So, no, no progress on this, sorry :-(

Tobias

Am 18.02.2012 um 23:23 schrieb "Kevin Smith" reply@reply.github.com:

**Comment by respectTheCode** [comment]
I feel like the new compiler is coming with 0.10.7. I just updated 2 of my projects to 0.10.6 without too many problems. I may take a stab at it when 0.10.7 comes out.

**Comment by tbosch** [comment]
Hi,
yes, let's see...

Tobias

---

Am 21.02.2012 um 15:21 schrieb Kevin Smith:

I feel like the new compiler is coming with 0.10.7. I just updated 2 of my projects to 0.10.6 without too many problems. I may take a stab at it when 0.10.7 comes out.

---

**Comment by rhuitl** [comment]
Hi,

I am working with the recently released JQM 1.1.0rc1 and Angular 1.0.0rc1 versions. Has there been any progress on making the adapter compatible with the new versions?

Robert

**Comment by tbosch** [comment]
Yes, just created a branch for angular 1.0.
Most parts should work already, expect for the paging in lists and `$navigate` expressions with promises (please use the `$navigate` service instead). 
Here is the link: https://github.com/tigbro/jquery-mobile-angular-adapter/blob/angular1.0/compiled/jquery-mobile-angular-adapter-1.0.7-SNAPSHOT.js

I would be glad about feedback!
Tobias

**Comment by rhuitl** [comment]
Tobias, thanks a lot, it's much appreciated. I will try the new version and report back results.

**Comment by tbosch** [comment]
Hi, 
almost everything should work now.
Please see the changelog: https://github.com/tigbro/jquery-mobile-angular-adapter/blob/angular1.0/Changelog.md
and the read me https://github.com/tigbro/jquery-mobile-angular-adapter/tree/angular1.0

Tobias

**Comment by tbosch** [comment]
Done with release 1.0.7 RC 1.
