### ISSUE TITLE
injection of $location results in failing page-refreshes

### ISSUE THREAD

**Issue by corsica** [opitzconsulting/jquery-mobile-angular-adapter#50]
I am not sure if this is a designed trade-off, but the (patched) $location service doesn't like to be injected into a controller.
For example, change the controller def of the 'todo-mobile' example, as such:

line 2: 
-- module.factory('todoStore', function ($http, $waitDialog) {
++module.factory('todoStore', function ($http, $waitDialog, $location) {

Navigate to /todo.html#settings, reload the page and see window.location go haywire.

**Comment by tbosch** [comment]
Hi, 
non, that's not by purpose! Thanks for reporting.

Here is a jsfiddle to reproduce this: http://jsfiddle.net/Du2DY/87/
Go to the page 'http://jsfiddle.net/Du2DY/87/show/#settings', reload it and look into the console.

Tobias

**Comment by corsica** [comment]
I see that in my reproduction-example (line 2) I don't inject into a controller but into a module. Has more or less the same effect though it seems. Here a little fork on jsfiddle with the injection on the controller ;-) http://jsfiddle.net/u4zw2/1/

**Comment by tbosch** [comment]
Thanks for reporting. Here is an updated jsfiddle with the 1.1.1-SNAPSHOT version: http://jsfiddle.net/u4zw2/3 resp. http://jsfiddle.net/u4zw2/3/show/

Please note: The new version has a different paged filter syntax. See the README.md for details.

Tobias
