### ISSUE TITLE
<textarea> fails during jQM page initialization

### ISSUE THREAD

**Issue by gscottolson** [opitzconsulting/jquery-mobile-angular-adapter#52]
I can't get <textarea> elements to render for a jQM page. It seems the failure is in the adapter, line 22400

cannot call methods on textinput prior to initialization; attempted to call method 'enable'

Here is a jsFiddle showing this error: http://jsfiddle.net/gscottolson/d967J/

**Comment by tbosch** [comment]
Hi,
thanks for reporting. Will look into this...

Tobias

**Comment by tbosch** [comment]
Here is an updated jsfiddle to show it is working.
http://jsfiddle.net/d967J/5/

Tobias
