### ISSUE TITLE
IE 8+

### ISSUE THREAD

**Issue by MicheleBertoli** [opitzconsulting/jquery-mobile-angular-adapter#53]
To make the library work on IE 8+ I had to modify the code at line 201 in this way:

```
        if (document.addEventListener) {
            document.addEventListener("DOMContentLoaded", callOnce, false);
        } else {
            callOnce();
        }

        // A fallback to window.onload, that will always work
        if (window.addEventListener) {
            window.addEventListener("load", callOnce);
        } else {
            callOnce();
        }
```

Otherwise, I got the following error:

Error: Object doesn't support property or method 'addEventListener'

**Comment by tbosch** [comment]
Hi,
did you test on IE9? addEventListener should work there... And Windows Phone Mange contains an IE9...

Tobias

**Comment by MicheleBertoli** [comment]
On IE9 the library works without problems.
Thanks for the answer,
Michele

**Comment by tbosch** [comment]
Closing this as we will not support IE8 in the future.

**Comment by jperl** [comment]
Unfortunately [IE8 share](http://www.w3counter.com/globalstats.php) is still > 5% and I have to support it :( Will you accept pull requests for IE8 fixes?

**Comment by rambocoder** [comment]
What's the point of doing ie8 fixes when windows mobile handsets have ie9+?

**Comment by jperl** [comment]
If you are targeting web and mobile.

**Comment by tbosch** [comment]
Hello jperl,
would be awesome if you could provide a pull request for this! I will reopen this issue for you.

Tobias

**Comment by jperl** [comment]
Sounds good. That project is coming up in about 2 weeks, so it will be a little time before then.
