### ISSUE TITLE
JQM 1.1.1 and jqmCompatMode(false)

### ISSUE THREAD

**Issue by joelwreed** [opitzconsulting/jquery-mobile-angular-adapter#54]
I had to add "$.mobile.linkBindingEnabled = false;" to this block in the locationProvider setup to get it to not fire the $.mobile.changePage event.

```
           $.mobile.linkBindingEnabled = false; // stop JQM changePage from firing                        
            // deactivate jqm hash listening and changing                                                  
        $.mobile.pushStateEnabled = false;
        $.mobile.hashListeningEnabled = false;
            $.mobile.changePage.defaults.changeHash = false;
```

**Comment by tbosch** [comment]
Hi, 
thanks for the input!
Sorry, I am very busy at the moment. I will review your solution soon. Could you create a jsfiddle for this? Would help a lot!

Tobias

**Comment by tbosch** [comment]
Yes, 
this was indeed a bug: If I click on a link, jqm called $.mobile.changePage, which it shouldn't with jqmCompatMode = false.
Thanks for reporting!
Tobias

**Comment by joelwreed** [comment]
Thanks for fixing this Tobias! Really appreciate your library.

Jr

**Comment by trebormat** [comment]
Thanks for this fix but I have always a problem with routeprovider. 
I set $locationProvider.jqmCompatMode(false);
The library adapter load the template but not changePage. I have some question about page id inside template:
In library code page id = template file name ? It doesn't work for me.
Also, in the example I found the lib jqmExternalAsEmbeddedPages. It's usable ?

Thanks for all.

**Comment by tbosch** [comment]
Hi,
could you try the new 1.2.0 version of the adapter? `$locationProvider.jqmCompatMode` is no more, have a look at the Readme.me...

For a simple example on using routes have a look at the todo js-fiddle.

The script `jqmExternalAsEmbeddedPages` is experimental and may be not up to date. But you can try :-)

Hope this helps,
Tobias

**Comment by trebormat** [comment]
It's working with the last version. 
Thanls for all
Matt
