### ISSUE TITLE
hasMore() doesn't work

### ISSUE THREAD

**Issue by emanuel-london** [opitzconsulting/jquery-mobile-angular-adapter#58]
See this: http://jsfiddle.net/nLcC6/2/
If you remove the hasMore() condition, and click on link it works just fine.

**Comment by tbosch** [comment]
Hi,
`hasMore` is a boolean, not a function. There was an error in the README.md, sorry. Here is the correct jsfiddle: http://jsfiddle.net/nLcC6/4/

By the way, your fiddle includes jquery-mobile-angular-adapter-standalone and angular. However, the standalone version already contains angular. 

Tobias
