### ISSUE TITLE
Close button in dialog with header doesn't work

### ISSUE THREAD

**Issue by jupiterplanet** [opitzconsulting/jquery-mobile-angular-adapter#62]
Hello Tobias,

I have found that the close button in dialogs with a header doesn't work. It just displays the label "Close" as a link but with no icon or button shape. Here is my jsFiddle: http://jsfiddle.net/jupiter/s7sGC/.

**Comment by tbosch** [comment]
Hi,
I am on holiday right now, will take care for this in 2 weeks...

Tobias

---

OPITZ CONSULTING München GmbH
Tobias Bosch - Solution Architect -
Diplominformatiker
Weltenburger Straße 4 | D-81677 München

Telefon +49 89 680098-0 | Fax +49 89 680098-4400
tobias.bosch@opitz-consulting.commailto:tobias.bosch@opitz-consulting.com
Twitter/Github: tigbro
www.opitz-consulting.comhttp://www.opitz-consulting.com/go/6-0-11

Standort Nürnberg
Färberstraße 20 | D-90402 Nürnberg
Fon +49 911 2528-490 | Fax +49 911 2528-492

Geschäftsführer: Bernhard Opitz
HRB-Nr. 127177 Amtsgericht München

---

Schaffen Sie Wettbewerbsvorteile mit Mobile Solutions!
Nutzen Sie die Chancen des Mobile Business? Haben Sie Mobile Solutions bereits in Ihre IT-Strategie integriert?

www.opitz-consulting.com/go_mobilehttp://www.opitz-consulting.com/go_mobile

Am 18.09.2012 um 22:44 schrieb jupiterplanet <notifications@github.com<mailto:notifications@github.com>>:

Hello Tobias,

I have found that the close button in dialogs with a header doesn't work. It just displays the label "Close" as a link but with no icon or button shape. Here is my jsFiddle: http://jsfiddle.net/jupiter/s7sGC/.

**Comment by tbosch** [comment]
Hi,
thanks for reporting this!
Yes, indeed, the icon is not rendered correctly.

However, a click on it works, see here: http://jsfiddle.net/s7sGC/1/

Tobias

---

OPITZ CONSULTING München GmbH
Tobias Bosch - Solution Architect -
Diplominformatiker
Weltenburger Straße 4 | D-81677 München

Telefon +49 89 680098-0 | Fax +49 89 680098-4400
tobias.bosch@opitz-consulting.commailto:tobias.bosch@opitz-consulting.com
Twitter/Github: tigbro
www.opitz-consulting.comhttp://www.opitz-consulting.com/go/6-0-11

Standort Nürnberg
Färberstraße 20 | D-90402 Nürnberg
Fon +49 911 2528-490 | Fax +49 911 2528-492

Geschäftsführer: Bernhard Opitz
HRB-Nr. 127177 Amtsgericht München

---

Schaffen Sie Wettbewerbsvorteile mit Mobile Solutions!
Nutzen Sie die Chancen des Mobile Business? Haben Sie Mobile Solutions bereits in Ihre IT-Strategie integriert?

www.opitz-consulting.com/go_mobilehttp://www.opitz-consulting.com/go_mobile

Am 18.09.2012 um 22:44 schrieb jupiterplanet <notifications@github.com<mailto:notifications@github.com>>:

Hello Tobias,

I have found that the close button in dialogs with a header doesn't work. It just displays the label "Close" as a link but with no icon or button shape. Here is my jsFiddle: http://jsfiddle.net/jupiter/s7sGC/.

**Comment by jupiterplanet** [comment]
No worries. Enjoy your holiday. You are right buttons functions correctly. It is just the rendering.

**Comment by JohannesRudolph** [comment]
Hi Tobias,

any update on this? Am currently dabbling with Angular (coming from backbone) and like it so far and this is one of the first issues I did hit.

Regards,
Johannes

**Comment by tbosch** [comment]
Almost done. Will commit the fix into the 1.1.2-SNAPSHOT today.

**Comment by tbosch** [comment]
Hi, 
here is an updated jsfiddle: [http://jsfiddle.net/s7sGC/2/](http://jsfiddle.net/s7sGC/2/)

Tobias

**Comment by tbosch** [comment]
The close button is styled, now, but the headline is not in the same row as the close button :-(

**Comment by JohannesRudolph** [comment]
That's a lot better now, however there's a small issue left, it seems the button doesn't get the right styling applied. 

Here's the raw HTMLs:

Plain JQM:

``` html
<a href="#" data-icon="delete" data-iconpos="notext" class="ui-btn-left ui-btn ui-shadow ui-btn-corner-all ui-btn-icon-notext ui-btn-up-a" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="a" title="Close"><span class="ui-btn-inner ui-btn-corner-all"><span class="ui-btn-text">Close</span><span class="ui-icon ui-icon-delete ui-icon-shadow">&nbsp;</span></span></a>
```

Angular.js + Adapter:

``` html
<a href="#" data-icon="delete" data-iconpos="notext" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="c" title="Close" class="ui-btn ui-btn-up-c ui-shadow ui-btn-corner-all ui-btn-icon-notext ui-btn-left"><span class="ui-btn-inner ui-btn-corner-all"><span class="ui-btn-text">Close</span><span class="ui-icon ui-icon-delete ui-icon-shadow">&nbsp;</span></span></a>
```

**Comment by JohannesRudolph** [comment]
Just hit another problem with the newest release: It seems that an ngm-click() specified on a button in the content section of the dialog doesn't get triggered anymore when clicking the button.

**Comment by tbosch** [comment]
Hi, 
this is a change in this release, please use ngm-vclick instead of ngm-click. By this we ate consistent with the event naming of jquery mobile. See the changelog. 

I'll look into the style differnces shortly. Are they just in the DOM, or are the changes also visible?
Tobias

**Comment by JohannesRudolph** [comment]
They're visible too. Thanks for the pointer re vclick.

Am 14.10.2012 um 18:22 schrieb Tobias Bosch notifications@github.com:

Hi,
this is a change in this release, please use ngm-vclick instead of
ngm-click. By this we ate consistent with the event naming of jquery
mobile. See the changelog.

I'll look into the style differnces shortly. Are they just in the DOM, or
are the changes also visible?
Tobias

—
Reply to this email directly or view it on
GitHubhttps://github.com/tigbro/jquery-mobile-angular-adapter/issues/62#issuecomment-9421249.
