### ISSUE TITLE
Make it extensible (or add more directives like vmousedown, etc)

### ISSUE THREAD

**Issue by icetbr** [opitzconsulting/jquery-mobile-angular-adapter#63]
I'd like to add at least vmousedown to "eventDirectives", but as it stands I have to do it manually

**Comment by tbosch** [comment]
Hi,
gut suggestion. Which other directives should exist? I'll add them...

Tobias

---

OPITZ CONSULTING München GmbH
Tobias Bosch - Solution Architect -
Diplominformatiker
Weltenburger Straße 4 | D-81677 München

Telefon +49 89 680098-0 | Fax +49 89 680098-4400
tobias.bosch@opitz-consulting.commailto:tobias.bosch@opitz-consulting.com
Twitter/Github: tigbro
www.opitz-consulting.comhttp://www.opitz-consulting.com/go/6-0-11

Standort Nürnberg
Färberstraße 20 | D-90402 Nürnberg
Fon +49 911 2528-490 | Fax +49 911 2528-492

Geschäftsführer: Bernhard Opitz
HRB-Nr. 127177 Amtsgericht München

---

Schaffen Sie Wettbewerbsvorteile mit Mobile Solutions!
Nutzen Sie die Chancen des Mobile Business? Haben Sie Mobile Solutions bereits in Ihre IT-Strategie integriert?

www.opitz-consulting.com/go_mobilehttp://www.opitz-consulting.com/go_mobile

Am 19.09.2012 um 16:52 schrieb icetbr <notifications@github.com<mailto:notifications@github.com>>:

I'd like to add at least vmousedown to "eventDirectives", but as it stands I have to do it manually

**Comment by icetbr** [comment]
Thanks for the reply! I like to use vmousedown instead of vclick because it makes for more responsive interfaces. Its the only one that I'm using right now. I don't mean to bloat your excelent library, but perhaps you should include them all? (http://jquerymobile.com/demos/1.1.0/docs/api/events.html)

Maybe just the virtual mouse events, something that distinguishes jQM.

vmouseover vmousedown vmousemove vmouseup vclick vmouseout vmousecancel

I also once had the need for the "pageinit", but that was before angular. I don't know if angular makes it irrelevant/difficult to implement.

Btw, I found myself with the same need on jquery and angular. I added ng-dragstart, ng-dragend and some others. I didn't looked for the reason why there are some events left out by default (read something about the blur and focus, that will be in the next release). I'm using a directive factory, much like the one from you're using.

**Comment by tbosch** [comment]
I'll add all events but the page change events (this is not the page transition events) and page initilization events, as they seem to be rather internal events that do not make sense to use in markup.

Tobias
