### ISSUE TITLE
Injecting $location and calling $navigate causes $digest recursion

### ISSUE THREAD

**Issue by mlegenhausen** [opitzconsulting/jquery-mobile-angular-adapter#64]
Hi,

my Problem is that I want to listen to location changes. So I inject the $location object. But when I then use the $navigate method I got the following digest recursion:

```
Error: 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [["fn: $locationWatch; newVal: 8; oldVal: 7"],["fn: $locationWatch; newVal: 9; oldVal: 8"],["fn: $locationWatch; newVal: 10; oldVal: 9"],["fn: $locationWatch; newVal: 11; oldVal: 10"],["fn: $locationWatch; newVal: 12; oldVal: 11"]]
    at Error (<anonymous>)
    at Object.Scope.$digest (http://localhost:8080/js/lib/angular/angular.js:7729:19)
    at Object.$rootScope.$digest (http://localhost:8080/js/lib/angular/jquery-mobile-angular-adapter.js:342:35)
    at Object.$rootScope.$digest (http://localhost:8080/js/lib/angular/jquery-mobile-angular-adapter.js:379:36)
    at Object.Scope.$apply (http://localhost:8080/js/lib/angular/angular.js:7894:24)
    at Object.$rootScope.$apply (http://localhost:8080/js/lib/angular/jquery-mobile-angular-adapter.js:334:31)
    at done (http://localhost:8080/js/lib/angular/angular.js:8883:20)
    at completeRequest (http://localhost:8080/js/lib/angular/angular.js:9023:7)
    at XMLHttpRequest.xhr.onreadystatechange (http://localhost:8080/js/lib/angular/angular.js:8993:11) 
```

I am using `$navigate('/some.html')` so not the hash variant.

The strange thing is that only the injection causes this error, so it happens even when I do not use the object. So something gets active when it gets injected. I am using version 1.1.1.

**Comment by mlegenhausen** [comment]
I was able to reproduce the bug in the todo example app.

https://github.com/mlegenhausen/todo-mobile

Simply start the angular jquery mobile app. Swipe to the left to open the settings, the bug should occur, when not click a second time on the link in the settings.html. Then the bug should definitely occur.

**Comment by tbosch** [comment]
Hi, 
there was a similar issue (#50). Did you use the 1.1.1 version of the adapter? Your todo-mobile fork contains the 1.1.0 version of the adapter...

Tobias

**Comment by mlegenhausen** [comment]
I am sorry, I thought I would use 1.1.1, but it is 1.1.0. I will check this tomorrow and give you feedback.

**Comment by mlegenhausen** [comment]
The Problem is even reproducable with angular 1.0.2 and jqm adapter 1.1.1. I updated my example. Simply follow the links in the example app. I removed all unnecessary code. I tested it in Chrome Beta 23.

The updated error message:

```
Uncaught Error: 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [["fn: $locationWatch; newVal: 8; oldVal: 7"],["fn: $locationWatch; newVal: 9; oldVal: 8"],["fn: $locationWatch; newVal: 10; oldVal: 9"],["fn: $locationWatch; newVal: 11; oldVal: 10"],["fn: $locationWatch; newVal: 12; oldVal: 11"]] angular.js:7729
Scope.$digest angular.js:7729
$rootScope.$digest jquery-mobile-angular-adapter.js:393
$rootScope.$digest jquery-mobile-angular-adapter.js:430
$.mobile.autoInitializePage jquery-mobile-angular-adapter.js:406
jQuery.event.dispatch jquery.js:3256
elemData.handle.eventHandle jquery.js:2875
jQuery.event.trigger jquery.js:3144
(anonymous function) jquery.js:3781
jQuery.extend.each jquery.js:658
jQuery.fn.jQuery.each jquery.js:271
jQuery.fn.extend.trigger jquery.js:3780
$.Widget._trigger jquery.mobile.js:1172
transitionPages jquery.mobile.js:2694
$.mobile.changePage jquery.mobile.js:3289
$.mobile.loadPage.done.fail.isPageTransitioning jquery.mobile.js:3161
fire jquery.js:1046
self.fireWith jquery.js:1164
self.fire jquery.js:1171
$.ajax.success jquery.mobile.js:3054
fire jquery.js:1046
self.fireWith jquery.js:1164
done jquery.js:7399
callback
```

**Comment by tbosch** [comment]
This can directly be reproduced by opening the url http://localhost:8080/todo-mobile/jquery-mobile-angular/index.html#/todo-mobile/jquery-mobile-angular/somethingelse.html.

**Comment by mlegenhausen** [comment]
Any ideas for a solution?

**Comment by tbosch** [comment]
Hi, if you use the 1.1.2-SNAPSHOT version this should work. At least it did when I put it into your application. 
This is kind of the same bug as #50, however I didn't test the loading of external jqm pages. As usual, I created an automatic test for this.

Thanks for reporting!
Tobias

**Comment by mlegenhausen** [comment]
Thanks tobias, I will try it out :)
