### ISSUE TITLE
navbar doesn't work with ng-repeat

### ISSUE THREAD

**Issue by jupiterplanet** [opitzconsulting/jquery-mobile-angular-adapter#65]
Hello Tobias,

I am trying to construct a jQuery mobile navbar with ng-repeat which doesnt' work. The active state of the buttons is not cleared. See this jsFiddle for a demonstration: http://jsfiddle.net/jupiter/v4Kt5/4/.

Cheers

**Comment by tbosch** [comment]
Hi,
thanks for reporting. Yes, this is really a bug.

Tobias

**Comment by tbosch** [comment]
Hi, 
here is an updated jsfiddle with the current snapshot version 1.1.2-SNAPSHOT.

Tobias

**Comment by jupiterplanet** [comment]
Thanks Tobias for this fast fix! Great work. I think you forgot the link for the updated jsfiddle.

**Comment by tbosch** [comment]
Hi, sorry, here is the link: http://jsfiddle.net/v4Kt5/6/ Tobias
