### ISSUE TITLE
Change page with parameter

### ISSUE THREAD

**Issue by fanalin** [opitzconsulting/jquery-mobile-angular-adapter#68]
Hi Tobias,

I really appreciate your work with the jqm/angular-adapter. Thank you!

I've updated this issue to reflect that I've solved my problem; the solution is below the problem-description.

Currently, I am looking for a nice and simple solution or design pattern for following problem:
I have "overview"- and "detail"-pages.
The overview-pages show lists of items, while the detail-pages show more details of one selected item (the selection happens by clicking on the overview-pages). The overview-pages and the detail-pages each have their own controller.
In the overview-pages, I would like to add a link to the detail-pages, which sets the selected item into the controller of the detail-page-controller and changes to the detail-page.

Solution:
The $navigate-service allows to call a function in target scope by adding a second and more parameters.

Best regards,
Matti

**Comment by tbosch** [comment]
Hi, 
yes, that's the right way!

Tobias

**Comment by jaumeavila** [comment]
Hi!
Matti, how do you change the page if this is in a different controller?
How do you specify in $navigate the controller where the page is in?

I can't find any documentation with an example for that.

Thanks!

Jaume.

**Comment by fanalin** [comment]
Hi,

see https://github.com/tigbro/jquery-mobile-angular-adapter#service-navigate
"If the activateFn function is given, it will be called after the navigation on the target page with activateParams as single argument. "

So just call $navigate("pageId", "functionNameToCallInTargetController", functionParameter)

Bye,
Matti

**Comment by jaumeavila** [comment]
Hi Matti!
Thanks so much for the quick response.

But my problem is that from inside a page with a specific controller I
can't go to a page that is bound to another controller.
If I wrap both pages under the same controller, then it works, but I need
each page to be run with a different controller.

Is that how is it supposed to be or is it me that I have something wrong?

Thanks so much!!!

Jaume

**Comment by fanalin** [comment]
Hi,

check this jsfiddle (it's my first one, so yell if it does not work): http://jsfiddle.net/FL5Wf/2/

As said above: inject the navigation-service to the first controller. Define a function, which takes the parameters in the scope of the second (child) controller. Now call $navigate("#idOfSecondPage", "nameOfFunctionToCall", "functionParameter"). 
Bye,
Matti

**Comment by jaumeavila** [comment]
You are the best Matti!

Do you know if there is a good place with examples using the jquery mobile
adapter?
I wasn't using before the adapter and I had som popup pages that were
displayed correctly, and now they are a mess.
I am developing a pretty complex web application and I am building the
interface, so I can take different approaches to list the data and how to
edit it.
And I was using a split listview, displaying in the header the title of an
item and in the split image at the right, I launched the popup, but now it
seems that does not work that well.

Well, I don't wanna bother you more, I just wondered if there is a page
where I can check out different interfaces that work ok with angular.

Thank you very much.  You helped me a lot!!!

Jaume
