### ISSUE TITLE
$waitDialog broken in 1.1.2 SNAPSHOT

### ISSUE THREAD

**Issue by JohannesRudolph** [opitzconsulting/jquery-mobile-angular-adapter#69]
Calling $waitDialog is broken in 1.1.2 Snapshost. The following JSFiddle reproduces the issue:

http://jsfiddle.net/cmPAv/

**Comment by JohannesRudolph** [comment]
Looking further into it, it seems its not solely an issue with $waitDialog but with $.mobile.loading. it seems jqms loaderWidget.loader is not initialized at the time the angular module controller definition is executed. jqm would initialize it on the pagecontainercreate event as far as I see... Seems we need to hook the adapter somewhere later into the pipeline.

**Comment by tbosch** [comment]
Hi,
thanks for reporting!
This only applies when you show the waitDialog in the constructor of your controller. Using the wait dialog in a click event does work: http://plnkr.co/edit/f6Yh6f

Still, I will also look into this...

Tobias

**Comment by JohannesRudolph** [comment]
Hi Tobias,
I noticed the same thing. I think it also only happens in controllers
loaded on the first page. Probably jqm has not finished initializing by
then or something...

**Comment by tbosch** [comment]
Hi, 
your initial jsfiddle works now and correctly shows the waitDialog.

Thanks for reporting,
Tobias
