### ISSUE TITLE
Buttons not rendered correctly

### ISSUE THREAD

**Issue by jupiterplanet** [opitzconsulting/jquery-mobile-angular-adapter#76]
Hi,

It seems that your latest snapshot 1.1.2-SNAPSHOT doesn't render buttons correctly with jQuery mobile 1.2.0 final.

I have prepared a jsFiddle: http://jsfiddle.net/jupiter/2vKcU/3/

I have encountered these issues so far:
1) When I add an icon with data-icon to an html button (button) the button text seems to be inserted into the icon span.
2) When I add an html input button (input type="text") the value is not used for the button title. Instead, no title is displayed.

Cheers

**Comment by tbosch** [comment]
Hi,
yes, this seems to be an open bug. Thanks for reporting!

Tobias
