### ISSUE TITLE
Button and input type button angular binding not working

### ISSUE THREAD

**Issue by pascalwhoop** [opitzconsulting/jquery-mobile-angular-adapter#80]
Hey!
Just as we talked over the phone, here a small jsfiddle:

http://jsfiddle.net/LpTQA/

Thanks for looking into it!

**Comment by tbosch** [comment]
Using the current snapshot version 1.1.2-SNAPSHOT, all buttons except for the `<input>` work.

**Comment by tbosch** [comment]
Updated js-fiddle: http://jsfiddle.net/LpTQA/1/
