### ISSUE TITLE
html5mode(true) is not working with PhoneGap

### ISSUE THREAD

**Issue by mlegenhausen** [opitzconsulting/jquery-mobile-angular-adapter#81]
I don't think it is an issue that you can fix, but it would be nice if you can add a note, that the default configuration of jqm-angular-adapter is not working on PhoneGap devices. The application is stopping after setting up the `$routeProvider` of jqm-angular-adapter.

The solution is to disable `html5mode`:

```
    // Fixes hang up bug when running the app via phonegap.
    app.config([
        '$locationProvider',
        function ($locationProvider) {
            $locationProvider.html5Mode(false);
        }
    ]);
```

The bug happens on android and iOS devices.

**Comment by tbosch** [comment]
Hi,
I think this is related to #72 which I just solved. Could you try again and report the exact error?

Thanks!
Tobias

**Comment by mlegenhausen** [comment]
Thanks tobias, that solved my problem! No problems any more with phonegap.
