### ISSUE TITLE
Horizontal controlgroup doesn't work.

### ISSUE THREAD

**Issue by jaumeavila** [opitzconsulting/jquery-mobile-angular-adapter#89]
When having an horizontal controlgroup, some errors are generated.

For example, this code does not work with the standalon version 1.1.2 but it worked with 1.1.1

<fieldset data-role="controlgroup" data-type="horizontal">
      <input type="radio" name="radio-choice" id="post_passenger" data-theme="d" checked="checked" value="0" />
      <label for="post_passenger">Pasajero</label>

      <input type="radio" name="radio-choice" id="post_driver" data-theme="d" value="1" />
      <label for="post_driver">Conductor</label>
    </fieldset>

Jaume

**Comment by tbosch** [comment]
The example from #55 

```
  <fieldset data-role="controlgroup" data-type="horizontal">
      <input type="radio" name="radio-choice" id="post_passenger" data-theme="d" checked="checked" value="0" />
      <label for="post_passenger">Pasajero</label>

      <input type="radio" name="radio-choice" id="post_driver" data-theme="d" value="1" />
      <label for="post_driver">Conductor</label>
</fieldset>
```

A workaround:

```
<div data-role="controlgroup" data-type="horizontal">
    <fieldset style="display:inline">
        <input type="radio" name="radio-choice" ng-model="radiochoice" id="post_passenger" data-theme="d" checked="checked" value="0" />
        <label for="post_passenger">Pasajero</label>
    </fieldset>

    <fieldset style="display:inline">
        <input type="radio" name="radio-choice" ng-model="radiochoice" id="post_driver" data-theme="d" value="1" />
        <label for="post_driver">Conductor</label>
    </fieldset>
</div>
```

It works, but when I do it for checkboxes they look too big. They don't llok the the jquery mobile horizontal toggle sets.
If you check the example at the bootom of the page http://jquerymobile.com/demos/1.2.0/docs/forms/checkboxes/ you can see that they look different.
Is there any way they look the same?

**Comment by tbosch** [comment]
This is working now, see this jsfiddle: http://jsfiddle.net/wDc9w/2/
