### ISSUE TITLE
Checkbox input styling broken

### ISSUE THREAD

**Issue by martindevans** [opitzconsulting/jquery-mobile-angular-adapter#90]
I've updated to jquery-mobile-angular-adapter-1.1.2-SNAPSHOT.js to fix another issue, and this has broken the styling on checkbox inputs within a fieldset.

I have a demo here of 2 checkboxes within a fieldset, the second one is clearly broken (and there is a large error in the javascript console):

http://www.placeholder-software.co.uk/static-files/.UI/Screens/MainMenu/MainMenu3.html

Here is a demo of the same two checkboxes, removed from the fieldset and working just fine:

http://www.placeholder-software.co.uk/static-files/.UI/Screens/MainMenu/MainMenu4.html

Here is a demo of the same two checkboxes but this time using jquery-mobile-angular-adapter-1.1.1.js

http://www.placeholder-software.co.uk/static-files/.UI/Screens/MainMenu/MainMenu5.html

**Comment by tbosch** [comment]
Hi, this is working now. I took the source code from your page and created a jsfiddle: http://jsfiddle.net/wDc9w/3/
