### ISSUE TITLE
shared-controller functionality combined with $navigate("#myPage", "sharedCtrl.function")

### ISSUE THREAD

**Issue by pascalwhoop** [opitzconsulting/jquery-mobile-angular-adapter#91]
Hey there. 
I noticed using a shared Ctrl together with your $navigate functionality is somewhat tricky.

If I try to call a function from a shared controller via the $navigate like this:

```
$navigate("#detailPage", "listsCtrl.setDetailItem")
```

It seems it only works with regular (angular) controllers however not with shared ones.

Just wanted to point it out. Would be a great thing to have.
Pascal

**Comment by tbosch** [comment]
Hi, 
`$navigate` is gone, but there are new function on `$location` instead. Migration guide: https://github.com/tigbro/jquery-mobile-angular-adapter/blob/master/Changelog.md

Also, the `onActivate` property on routes is now an expression, i.e. this can call also functions in a shared controller.

Here is a jsfiddle that uses a shared controller on the new onActivate expression: http://jsfiddle.net/FL5Wf/7/
Tobias
