### ISSUE TITLE
Page transitions not working in IE10

### ISSUE THREAD

**Issue by johnnyelwailer** [opitzconsulting/jquery-mobile-angular-adapter#94]
Page css transitions do not work on IE10  with latest version of angular adapter and jquery mobile 1.2 (which supports transitions on IE10, tested it on their demo page)

See this modified sample of the todo app (using latest snapshot).
http://plnkr.co/edit/1KFoEOEzxFVvj4pW19I0?p=preview

**Comment by tbosch** [comment]
Hi,
just tried IE10, and did no get transitions also without angular and the adapter.
Could you provide a simple jsfiddle only with jquery mobile where transitions work?

Tobias

**Comment by johnnyelwailer** [comment]
Hi
You are right... It worked before on their demo page(though their current demo page, v1.2, it doesn't work using ie10, so maybe I was looking at a preview version).
The transitions are now running using jqm 1.3... so never mind. :)

**Comment by tbosch** [comment]
Hi,
please be aware that the adapter is not jqm 1.3 compatible yet, although most of it should work fine. See the other issues regarding jqm 1.3 for the adapter. I will do a full jqm 1.3 check this or next month...

Thanks,
Tobias
