### ISSUE TITLE
ngm-if broken with angular.js 1.0.3

### ISSUE THREAD

**Issue by JohannesRudolph** [opitzconsulting/jquery-mobile-angular-adapter#97]
Hi tigbro, really hope I'm not annoying you with opening issues.

This time, ngm-if stopped working with angular.js 1.0.3: http://jsfiddle.net/ErhC5/3/
Replacing angularjs with 1.0.2 will make the fiddle work.

I'd love to supply you with pull requests in the future, finally trying to setup my build environment for the adapter...

**Comment by tbosch** [comment]
Hi,
here is a fiddle with the updated jqm version (cutting the 1.2.0 release right now :-) )

Thanks, you are a really great help!
Tobias
