### ISSUE TITLE
Build system: Remove Maven, use node-js and Travis-CI

### ISSUE THREAD

**Issue by tbosch** [opitzconsulting/jquery-mobile-angular-adapter#98]
We are already using node-js for the concatenation and minification part. 
Travis-CI would be great to make it easier to contribute to the project.

**Comment by mlegenhausen** [comment]
How about testacular and grunt?

**Comment by tbosch** [comment]
Yes, that's a good idea!

**Comment by mlegenhausen** [comment]
This would make contributions easier.
Do you have a migration branch? Maybe I can support you.

**Comment by tbosch** [comment]
Hi,
not yet, sorry. But thanks, I will come back to you when I start this ticket!

Tobias

**Comment by tbosch** [comment]
Hi,
here is a branch for doing this: https://github.com/tigbro/jquery-mobile-angular-adapter/tree/new_build_system

Would be great if you could try and create some pull requests for this. If you need help, please let me know!

Thanks,
Tobias

**Comment by mlegenhausen** [comment]
Thanks Tobias, I will give you feedback when I find the time to work on it.
