### ISSUE TITLE
Custom select menu dialog won't close in multi-page context

### ISSUE THREAD

**Issue by blasky** [opitzconsulting/jquery-mobile-angular-adapter#99]
Took me a while to boil this one down. The fiddle below follows the basic "multi-page" format for mobile (...and is essentially the same as the working fiddle for Issue #83).

http://jsfiddle.net/ad47J/

There is a main page and a dialog page. In addition, the main page now contains a large custom select menu.
1. If you go from the main page to the dialog, you can return using the "Go Back" button. Check.
2. If you go from the main page to the dialog, you can return using the dialog closing X in the upper left. Check.
3. If you pull up the select menu dialog and select an option, you return to the main page with your new selection in place. Check.
4. However...if you pull up the select menu dialog, the dialog closing X in the upper left does not function.

This dialog closing X works in a single page context like the working fiddle for Issue #75. It appears to be the multi-page context that trips things up.

(I saw that you added custom closing / navigation code for the dialog case in general. It may be that the select menu dialog generated by mobile needs a similar patch of some sort.)

Thanks so much. Happy holidays.

**Comment by tbosch** [comment]
Hi,
yes, this seems to be a bug still, sorry, somehow I did forget to add a test for this in the refactoring of the routing system.

Thanks for reporting!
Tobias

**Comment by blasky** [comment]
No worries. Looking forward to it.

**Comment by tbosch** [comment]
Hi, 
this should work now with the version 1.2.1-SNAPSHOT.js. See this fiddle: http://jsfiddle.net/ad47J/1/

Tobias

**Comment by blasky** [comment]
Looks good in my code. Thanks again.
